name: 'Maven Central Publish'
description: 'Publishes a Maven project to Maven Central repository.'

inputs:
  GPG-PRIVATE-KEY:
    description: 'GPG-PRIVATE-KEY'
    required: true
    default: "EMPTY"
  GPG-PASSPHRASE:
    description: 'GPG-PASSPHRASE'
    required: true
    default: "EMPTY"
  MAVEN-USERNAME:
    description: 'MAVEN-USERNAME'
    required: true
    default: "EMPTY"
  MAVEN-PASSWORD:
    description: 'MAVEN-PASSWORD'
    required: true
    default: "EMPTY"


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GPG-PRIVATE-KEY }}
    - ${{ inputs.GPG-PASSPHRASE }}
    - ${{ inputs.MAVEN-USERNAME }}
    - ${{ inputs.MAVEN-PASSWORD }}