name: 'Maven Central Publish'
description: 'Publishes a Maven project to Maven Central repository.'

inputs:
  GPG_PRIVATE_KEY:
    description: 'GPG_PRIVATE_KEY'
    required: true
  GPG_PASSPHRASE:
    description: 'GPG_PASSPHRASE'
    required: true
  MAVEN_USERNAME:
    description: 'MAVEN_USERNAME'
    required: true
  MAVEN_PASSWORD:
    description: 'MAVEN_PASSWORD'
    required: true


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GPG_PRIVATE_KEY: ${{ inputs.GPG_PRIVATE_KEY }}
    GPG_PASSPHRASE: ${{ inputs.GPG_PASSPHRASE }}
    MAVEN_USERNAME: ${{ inputs.MAVEN_USERNAME }}
    MAVEN_PASSWORD: ${{ inputs.MAVEN_PASSWORD }}