name: 'Maven Central Publish'
description: 'Publishes a Maven project to Maven Central repository.'

inputs:
  GPG_PASSPHRASE:
    description: 'GPG_PASSPHRASE'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'