name: 'Maven Central Publish'
description: 'Publishes a Maven project to Maven Central repository.'

inputs:
  GPG_PRIVATE_KEY:
    description: 'GPG_PRIVATE_KEY'
    required: true
    default: "EMPTY"
  GPG_PASSPHRASE:
    description: 'GPG_PASSPHRASE'
    required: true
    default: "EMPTY"
  MAVEN_USERNAME:
    description: 'MAVEN_USERNAME'
    required: true
    default: "EMPTY"
  MAVEN_PASSWORD:
    description: 'MAVEN_PASSWORD'
    required: true
    default: "EMPTY"


runs:
  using: 'docker'
  image: 'Dockerfile'
  args: |
    - ${{ inputs.GPG_PRIVATE_KEY }}
    - ${{ inputs.GPG_PASSPHRASE }}
    - ${{ inputs.MAVEN_USERNAME }}
    - ${{ inputs.MAVEN_PASSWORD }}