name: Publish to Maven Central
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Write Secret to File
        run: echo "$GPG_PRIVATE_KEY"
        env:
          GPG_PRIVATE_KEY: ${{ vars.name }}

      - name: Maven Central Publish
        uses: ./ # 使用当前仓库中的 Action
        with:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

