name: Publish to Maven Central
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Maven Central Publish
        uses: ./ # 使用当前仓库中的 Action
