name: Publish to Maven Central
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: List files in target directory
        run: ls -l /github/workspace/target
      - name: Maven Central Publish
        uses: ./ # 使用当前仓库中的 Action
